---
layout: default
title: Christina Restrepo Nazar - Academic Portfolio
---

![Featured Image](img_0083.jpg)

# Christina Restrepo Nazar, Ph.D. 
## Graduate Research Associate 

### About Me
I am currently a graduate research associate at the University of Central Florida, where I am pursuing a Ph.D. in Texts and Technology. 

### Research Interests
- STEM Education/Teacher Education
- Digital Humanities
- Artificial Intelligence 

### Publications and/or Conferences

1. Paper Title, Journal, Year
2. Another Paper Title, Conference, Year

### Contact

- Email: your-email@example.com
- Office: Your office location

### Follow Me

- [Bluesky](https://bsky.app/your_bluesky_handle)
- [LinkedIn](https://linkedin.com/in/your_linkedin_profile)
- [GitHub](https://github.com/your_github_username)


